"""empty message

Revision ID: 098c3bad832a
Revises: 03434eff4ae6
Create Date: 2024-02-07 15:18:41.154135

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '098c3bad832a'
down_revision = '03434eff4ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_status'), ['status'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('ix_customer_status')

    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False),
    sa.Column('type', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('document', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('status', mysql.ENUM('disabled', 'enabled', 'deleted', 'inactive'), server_default=sa.text("'enabled'"), nullable=True),
    sa.Column('date_create', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('ix_customer_status', ['status'], unique=False)
        batch_op.create_index('email', ['email'], unique=True)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_status'))

    op.drop_table('customers')
    # ### end Alembic commands ###
