"""empty message

Revision ID: 09f2a16f171e
Revises: f42d7db110be
Create Date: 2024-02-06 14:03:00.759652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '09f2a16f171e'
down_revision = 'f42d7db110be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('country_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('language_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('segment', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=28), nullable=True),
    sa.Column('timezone', sa.String(length=40), server_default='America/Sao_Paulo', nullable=True),
    sa.Column('avatar_path', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='json extra data'),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('ip', sa.String(length=39), nullable=False, comment='ip address used in signup'),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_status'))

    op.drop_table('partners')
    # ### end Alembic commands ###
