"""empty message

Revision ID: 0dd59f53416c
Revises: 9f9566b7c363
Create Date: 2025-08-01 16:12:39.716175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0dd59f53416c'
down_revision = '9f9566b7c363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cateory_id', mysql.INTEGER(unsigned=True), nullable=False))
        batch_op.create_foreign_key(None, 'categories', ['cateory_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cateory_id')

    # ### end Alembic commands ###
