"""empty message

Revision ID: 0ff15af92120
Revises: 67d60325a539
Create Date: 2024-11-18 14:44:58.788453

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0ff15af92120'
down_revision = '67d60325a539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=80), nullable=False))
        batch_op.drop_column('basket_description')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=40), nullable=False))
        batch_op.drop_index('unit_description')
        batch_op.create_unique_constraint(None, ['description'])
        batch_op.drop_column('unit_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('unit_description', ['unit_description'], unique=True)
        batch_op.drop_column('description')

    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basket_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
