"""empty message

Revision ID: 11b75e923ddd
Revises: b8d8d6b5eb0e
Create Date: 2025-07-21 14:09:52.403163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11b75e923ddd'
down_revision = 'b8d8d6b5eb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['clients.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_status'), ['status'], unique=False)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.DECIMAL(precision=15, scale=0), nullable=True))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', mysql.DECIMAL(precision=15, scale=0), nullable=True))
        batch_op.drop_column('quantity')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_status'))

    op.drop_table('sessions')
    # ### end Alembic commands ###
