"""empty message

Revision ID: 11f1833ac440
Revises: 81761e921367
Create Date: 2024-03-01 16:43:41.067515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f1833ac440'
down_revision = '81761e921367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('date_create')

    # ### end Alembic commands ###
