"""add email_optin to checkout

Revision ID: 12e198d0c100
Revises: bc77f8739b57
Create Date: 2026-04-30 11:33:02.486107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12e198d0c100'
down_revision = 'bc77f8739b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_optin', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=True)

    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.drop_column('email_optin')

    # ### end Alembic commands ###
