"""add email, remove name e phone do checkout

Revision ID: 154c9f869763
Revises: 1726f885662d
Create Date: 2026-04-30 10:48:59.701356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154c9f869763'
down_revision = '1726f885662d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
