"""empty message

Revision ID: 15a528a377d5
Revises: db9502ab94ef
Create Date: 2026-05-11 11:57:32.115149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15a528a377d5'
down_revision = 'db9502ab94ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('pwd',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=28),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('pwd',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=28),
               existing_nullable=True)
        batch_op.alter_column('user_name',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
