"""remove delivery_date delivery_time, rename dados pessoais

Revision ID: 1726f885662d
Revises: 44ebea258389
Create Date: 2026-04-30 10:40:38.534932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1726f885662d'
down_revision = '44ebea258389'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.drop_column('delivery_time')
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('delivery_time', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False))

    # ### end Alembic commands ###
