"""empty message

Revision ID: 1896d26eae14
Revises: da5cb5c192b6
Create Date: 2025-07-29 14:45:56.353918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1896d26eae14'
down_revision = 'da5cb5c192b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('category_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_type', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
