"""empty message

Revision ID: 1918f37d6fb3
Revises: ca87cda0d1e6
Create Date: 2024-07-10 14:13:16.647655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1918f37d6fb3'
down_revision = 'ca87cda0d1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_constraint('baskets_ibfk_2', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('baskets_ibfk_2', 'products', ['product_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###
