"""empty message

Revision ID: 1fb1bb679e07
Revises: 765b5ec33064
Create Date: 2024-12-13 16:19:20.124718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1fb1bb679e07'
down_revision = '765b5ec33064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=15, scale=0), nullable=False),
    sa.Column('voucher', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('discount', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('subtotal', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('delivery', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('payment_code', sa.String(length=40), nullable=True),
    sa.Column('date_delivery', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_code'),
    sa.UniqueConstraint('time_slot'),
    sa.UniqueConstraint('uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkout_status'), ['status'], unique=False)

    op.create_table('checkout_basket',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('basket_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.drop_table('cart_basket')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index('ix_cart_status')
        batch_op.drop_index('payment_code')
        batch_op.drop_index('time_slot')
        batch_op.drop_index('uuid')

    op.drop_table('cart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('value', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('voucher', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', mysql.ENUM('disabled', 'enabled', 'deleted', 'inactive'), server_default=sa.text("'enabled'"), nullable=True),
    sa.Column('payment_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=False),
    sa.Column('date_delivery', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('time_slot', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('date_create', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index('uuid', ['uuid'], unique=True)
        batch_op.create_index('time_slot', ['time_slot'], unique=True)
        batch_op.create_index('payment_code', ['payment_code'], unique=True)
        batch_op.create_index('ix_cart_status', ['status'], unique=False)

    op.create_table('cart_basket',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('cart_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('basket_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('date_create', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name='cart_basket_ibfk_1', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='cart_basket_ibfk_2', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('checkout_basket')
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkout_status'))

    op.drop_table('checkout')
    # ### end Alembic commands ###
