"""empty message

Revision ID: 23220fc724da
Revises: 15a528a377d5
Create Date: 2026-05-12 08:46:56.505155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '23220fc724da'
down_revision = '15a528a377d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_slug'))
        batch_op.drop_index(batch_op.f('slug'))
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.create_index(batch_op.f('slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('idx_slug'), ['slug'], unique=True)
        batch_op.alter_column('size',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40),
               existing_nullable=True)

    # ### end Alembic commands ###
