"""empty message

Revision ID: 268d283ecd2c
Revises: 9034d1a7281f
Create Date: 2024-03-08 11:10:23.896076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268d283ecd2c'
down_revision = '9034d1a7281f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True))
        batch_op.create_index(batch_op.f('ix_client_gifted_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_gifted_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
