"""empty message

Revision ID: 28210e826e93
Revises: 7f267b0f5bba
Create Date: 2024-06-06 09:07:31.330438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28210e826e93'
down_revision = '7f267b0f5bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_name', sa.String(length=40), nullable=False),
    sa.Column('pwd', sa.String(length=28), nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index('uuid')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False))
        batch_op.add_column(sa.Column('gifted_ocasion', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('gifted_message', sa.Text(), nullable=True, comment='message'))
        batch_op.add_column(sa.Column('code_country', sa.String(length=4), server_default='55', nullable=True))
        batch_op.add_column(sa.Column('code_area', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True))
        batch_op.alter_column('gifted_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=True)
        batch_op.alter_column('signature_card',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=True)
        batch_op.drop_index('uuid')
        batch_op.create_index(batch_op.f('ix_client_gifted_status'), ['status'], unique=False)
        batch_op.drop_constraint('client_gifted_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'], onupdate='CASCADE')
        batch_op.drop_column('uuid')
        batch_op.drop_column('gift_ocasion')
        batch_op.drop_column('gifted_id')
        batch_op.drop_column('message')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['uuid'])
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['type'])

    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_index('uuid')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=False))
        batch_op.add_column(sa.Column('size', sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column('path', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True))
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], onupdate='CASCADE')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True))
        batch_op.create_index(batch_op.f('ix_units_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_products_status'))
        batch_op.drop_column('status')
        batch_op.drop_column('path')
        batch_op.drop_column('size')
        batch_op.drop_column('category_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
        batch_op.create_index('uuid', ['uuid'], unique=True)

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('type')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='message'))
        batch_op.add_column(sa.Column('gifted_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gift_ocasion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False))
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('client_gifted_ibfk_1', 'clients', ['gifted_id'], ['id'], onupdate='CASCADE')
        batch_op.drop_index(batch_op.f('ix_client_gifted_status'))
        batch_op.create_index('uuid', ['uuid'], unique=True)
        batch_op.alter_column('signature_card',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=False)
        batch_op.alter_column('gifted_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('number')
        batch_op.drop_column('code_area')
        batch_op.drop_column('code_country')
        batch_op.drop_column('gifted_message')
        batch_op.drop_column('gifted_ocasion')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
        batch_op.create_index('uuid', ['uuid'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))

    op.drop_table('users')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_status'))

    op.drop_table('categories')
    # ### end Alembic commands ###
