"""empty message

Revision ID: 29b644be9590
Revises: 11f1833ac440
Create Date: 2024-03-01 23:35:45.392815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29b644be9590'
down_revision = '11f1833ac440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('uuid')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=False))
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))

    # ### end Alembic commands ###
