"""empty message

Revision ID: 2deee5a55c7b
Revises: ff34e4ea4bc2
Create Date: 2024-02-22 11:27:09.485898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2deee5a55c7b'
down_revision = 'ff34e4ea4bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.alter_column('type',
               existing_type=mysql.INTEGER(unsigned=True),
               type_=sa.String(length=2),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['type'])
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['uuid'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('type',
               existing_type=sa.String(length=2),
               type_=mysql.INTEGER(unsigned=True),
               existing_nullable=False)
        batch_op.drop_column('uuid')

    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
