"""empty message

Revision ID: 2e2d6ba1d13e
Revises: 23220fc724da
Create Date: 2026-05-19 08:21:18.289699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e2d6ba1d13e'
down_revision = '23220fc724da'
branch_labels = None
depends_on = None

def upgrade():
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))
        batch_op.create_index(batch_op.f('idx_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('description'), ['description'], unique=True)

    # ### end Alembic commands ###
