"""empty message

Revision ID: 2ea6f93bd5ff
Revises: 75b52dd77001
Create Date: 2024-12-19 11:25:42.190972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ea6f93bd5ff'
down_revision = '75b52dd77001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=15, scale=0),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True)
        batch_op.alter_column('delivery',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=True)
        batch_op.drop_index('payment_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout', schema=None) as batch_op:
        batch_op.create_index('payment_code', ['payment_code'], unique=True)
        batch_op.alter_column('delivery',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False)
        batch_op.alter_column('subtotal',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=15, scale=0),
               nullable=False)
        batch_op.alter_column('value',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               nullable=False)

    # ### end Alembic commands ###
