"""empty message

Revision ID: 2feb234d1018
Revises: 
Create Date: 2024-02-05 10:00:11.396688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2feb234d1018'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('official_name', sa.String(length=60), nullable=True),
    sa.Column('alpha_2', sa.String(length=2), nullable=True),
    sa.Column('alpha_3', sa.String(length=3), nullable=False),
    sa.Column('numeric_ref', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_countries_alpha_3'), 'countries', ['alpha_3'], unique=False)
    op.create_index(op.f('ix_countries_numeric_ref'), 'countries', ['numeric_ref'], unique=False)
    op.create_table('currencies',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('alpha_3', sa.String(length=3), nullable=False),
    sa.Column('numeric_ref', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_currencies_alpha_3'), 'currencies', ['alpha_3'], unique=False)
    op.create_table('languages',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('alpha_3', sa.String(length=3), nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_table('addresses',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('country_id', mysql.SMALLINT(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('street', sa.String(length=80), nullable=False),
    sa.Column('street_number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=30), nullable=True),
    sa.Column('type', sa.Enum('home', 'contact', 'comercial', name='addresstypeenum'), server_default='contact', nullable=True),
    sa.Column('is_verified', sa.Enum('false', 'true', name='booleanenum'), server_default='false', nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('last_update', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_addresses_status'), 'addresses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_addresses_status'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_table('languages')
    op.drop_index(op.f('ix_currencies_alpha_3'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_countries_numeric_ref'), table_name='countries')
    op.drop_index(op.f('ix_countries_alpha_3'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
