"""empty message

Revision ID: 319f2b6fd614
Revises: 012bae020455
Create Date: 2026-05-19 08:46:37.656594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319f2b6fd614'
down_revision = '012bae020455'
branch_labels = None
depends_on = None

def upgrade():
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###
