"""empty message

Revision ID: 3251cb8454f3
Revises: 0dd59f53416c
Create Date: 2025-08-04 10:30:04.135662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3251cb8454f3'
down_revision = '0dd59f53416c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('cateory_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cateory_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('products_ibfk_3'), 'categories', ['cateory_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###
