"""empty message

Revision ID: 33ec7c470915
Revises: 
Create Date: 2024-11-05 10:32:31.379331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33ec7c470915'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=40), nullable=False),
    sa.Column('category_type', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_status'), ['status'], unique=False)

    op.create_table('clients',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=2), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('document', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('type'),
    sa.UniqueConstraint('uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_status'), ['status'], unique=False)

    op.create_table('countries',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('official_name', sa.String(length=60), nullable=True),
    sa.Column('alpha_2', sa.String(length=2), nullable=True),
    sa.Column('alpha_3', sa.String(length=3), nullable=False),
    sa.Column('numeric_ref', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_alpha_3'), ['alpha_3'], unique=False)
        batch_op.create_index(batch_op.f('ix_countries_numeric_ref'), ['numeric_ref'], unique=False)

    op.create_table('currencies',
    sa.Column('id', mysql.SMALLINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('alpha_3', sa.String(length=3), nullable=False),
    sa.Column('numeric_ref', mysql.SMALLINT(unsigned=True), nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_currencies_alpha_3'), ['alpha_3'], unique=False)

    op.create_table('languages',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('alpha_3', sa.String(length=3), nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_table('phones',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('code_country', sa.String(length=4), server_default='55', nullable=False),
    sa.Column('code_area', sa.String(length=4), nullable=False),
    sa.Column('number', sa.String(length=15), nullable=False),
    sa.Column('type', sa.Enum('home', 'contact', 'comercial', 'mobile', name='phonetypeenum'), server_default='contact', nullable=True),
    sa.Column('is_verified', sa.Enum('false', 'true', name='booleanenum'), server_default='false', nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('last_update', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phones_status'), ['status'], unique=False)

    op.create_table('sales',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('voucher', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('payment_code', sa.String(length=40), nullable=False),
    sa.Column('date_delivery', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('time_slot', sa.String(length=20), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_code'),
    sa.UniqueConstraint('time_slot'),
    sa.UniqueConstraint('uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_status'), ['status'], unique=False)

    op.create_table('units',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_status'), ['status'], unique=False)

    op.create_table('addresses',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('country_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=60), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('street', sa.String(length=80), nullable=False),
    sa.Column('street_number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=30), nullable=True),
    sa.Column('type', sa.Enum('home', 'contact', 'comercial', name='addresstypeenum'), server_default='contact', nullable=True),
    sa.Column('is_verified', sa.Enum('false', 'true', name='booleanenum'), server_default='false', nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('last_update', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_status'), ['status'], unique=False)

    op.create_table('baskets',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baskets_status'), ['status'], unique=False)

    op.create_table('client_gifted',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('gifted_name', sa.String(length=80), nullable=True),
    sa.Column('gifted_ocasion', sa.String(length=80), nullable=True),
    sa.Column('signature_card', sa.String(length=80), nullable=True),
    sa.Column('gifted_message', sa.Text(), nullable=True, comment='message'),
    sa.Column('code_country', sa.String(length=4), server_default='55', nullable=True),
    sa.Column('code_area', sa.String(length=4), nullable=True),
    sa.Column('number', sa.String(length=15), nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_gifted_status'), ['status'], unique=False)

    op.create_table('client_messages',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=True, comment='message'),
    sa.Column('priority', sa.Enum('normal', 'high', 'low', name='messagepriorityenum'), server_default='normal', nullable=True),
    sa.Column('state', sa.Enum('new', 'shown', 'hidden', 'deleted', 'archived', name='messagestatusenum'), server_default='new', nullable=True),
    sa.Column('favorite', sa.Enum('false', 'true', name='booleanenum'), server_default='false', nullable=True),
    sa.Column('is_pushable', sa.Enum('false', 'true', name='booleanenum'), server_default='false', nullable=True),
    sa.Column('push_sended', sa.Enum('false', 'true', name='booleanenum'), server_default='false', nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('client_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_messages_favorite'), ['favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_messages_is_pushable'), ['is_pushable'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_messages_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_messages_push_sended'), ['push_sended'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_messages_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_messages_status'), ['status'], unique=False)

    op.create_table('client_phones',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('phone_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_table('partners',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('country_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('language_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('segment', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=28), nullable=True),
    sa.Column('timezone', sa.String(length=40), server_default='America/Sao_Paulo', nullable=True),
    sa.Column('avatar_path', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True, comment='json extra data'),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('ip', sa.String(length=39), nullable=False, comment='ip address used in signup'),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partners_status'), ['status'], unique=False)

    op.create_table('products',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('unit_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('size', sa.Numeric(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.Column('value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('user_name', sa.String(length=40), nullable=False),
    sa.Column('pwd', sa.String(length=28), nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('basket_products',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('basket_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_table('client_addresses',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('address_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_table('partner_clients',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('partner_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('clients_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['clients_id'], ['clients.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_table('partner_phones',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('partner_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('phone_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_table('partner_products',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('partner_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('products_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['products_id'], ['products.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    op.create_table('sale_products',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('sale_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_products')
    op.drop_table('partner_products')
    op.drop_table('partner_phones')
    op.drop_table('partner_clients')
    op.drop_table('client_addresses')
    op.drop_table('basket_products')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_status'))

    op.drop_table('products')
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partners_status'))

    op.drop_table('partners')
    op.drop_table('client_phones')
    with op.batch_alter_table('client_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_messages_status'))
        batch_op.drop_index(batch_op.f('ix_client_messages_state'))
        batch_op.drop_index(batch_op.f('ix_client_messages_push_sended'))
        batch_op.drop_index(batch_op.f('ix_client_messages_priority'))
        batch_op.drop_index(batch_op.f('ix_client_messages_is_pushable'))
        batch_op.drop_index(batch_op.f('ix_client_messages_favorite'))

    op.drop_table('client_messages')
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_gifted_status'))

    op.drop_table('client_gifted')
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baskets_status'))

    op.drop_table('baskets')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_status'))

    op.drop_table('addresses')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_status'))

    op.drop_table('units')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_status'))

    op.drop_table('sales')
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phones_status'))

    op.drop_table('phones')
    op.drop_table('languages')
    with op.batch_alter_table('currencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_currencies_alpha_3'))

    op.drop_table('currencies')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_numeric_ref'))
        batch_op.drop_index(batch_op.f('ix_countries_alpha_3'))

    op.drop_table('countries')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_status'))

    op.drop_table('clients')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_status'))

    op.drop_table('categories')
    # ### end Alembic commands ###
