"""empty message

Revision ID: 39061671c67b
Revises: 2e2d6ba1d13e
Create Date: 2026-05-19 08:37:56.375818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39061671c67b'
down_revision = '2e2d6ba1d13e'
branch_labels = None
depends_on = None

def upgrade():
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_categories_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###
