"""empty message

Revision ID: 3967825f1d9b
Revises: d21aca8cd6f8
Create Date: 2024-03-07 17:27:59.708262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3967825f1d9b'
down_revision = 'd21aca8cd6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gifted_message', sa.Text(), nullable=True, comment='message'))
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='message'))
        batch_op.drop_column('gifted_message')

    # ### end Alembic commands ###
