"""empty message

Revision ID: 44ebea258389
Revises: 47ab1f5e5e79
Create Date: 2026-04-24 09:54:46.204284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44ebea258389'
down_revision = '47ab1f5e5e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               nullable=True)
        batch_op.drop_index(batch_op.f('type'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('type'), ['type'], unique=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               nullable=False)

    # ### end Alembic commands ###
