"""empty message

Revision ID: 45cec15309bb
Revises: 3251cb8454f3
Create Date: 2025-08-04 10:41:57.588862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45cec15309bb'
down_revision = '3251cb8454f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_categories', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False))

    # ### end Alembic commands ###
