"""empty message

Revision ID: 47ab1f5e5e79
Revises: 45cec15309bb
Create Date: 2026-04-24 09:02:05.785750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47ab1f5e5e79'
down_revision = '45cec15309bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkouts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('order_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('address_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('delivery_time', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('payment_method', sa.Enum('pix', 'credit_card', 'debit_card', name='paymentmethodenum'), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='paymentstatusenum'), server_default='pending', nullable=True),
    sa.Column('payment_external_id', sa.String(length=100), nullable=True),
    sa.Column('total_value', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkouts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkouts_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkouts_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkouts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkouts_status'))
        batch_op.drop_index(batch_op.f('ix_checkouts_payment_status'))
        batch_op.drop_index(batch_op.f('ix_checkouts_order_id'))
        batch_op.drop_index(batch_op.f('ix_checkouts_client_id'))

    op.drop_table('checkouts')
    # ### end Alembic commands ###
