"""empty message

Revision ID: 4832146f45ac
Revises: 1896d26eae14
Create Date: 2025-07-31 09:41:50.010829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4832146f45ac'
down_revision = '1896d26eae14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('products_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('products_ibfk_1'), 'categories', ['category_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###
