"""empty message

Revision ID: 4ae848929101
Revises: 4fbddbe39163
Create Date: 2024-03-01 10:32:18.023065

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ae848929101'
down_revision = '4fbddbe39163'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               nullable=True)
        batch_op.alter_column('date_create',
               existing_type=mysql.DECIMAL(precision=15, scale=3),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('date_create',
               existing_type=mysql.DECIMAL(precision=15, scale=3),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2),
               nullable=False)
        batch_op.alter_column('uuid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               nullable=False)

    # ### end Alembic commands ###
