"""empty message

Revision ID: 4da2952e8641
Revises: 5063cae65e7e
Create Date: 2026-06-01 20:16:33.436944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4da2952e8641'
down_revision = '5063cae65e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=mysql.INTEGER(unsigned=True),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###
