"""empty message

Revision ID: 4fbddbe39163
Revises: e379e4f22113
Create Date: 2024-03-01 10:28:23.486918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fbddbe39163'
down_revision = 'e379e4f22113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False))
        batch_op.create_unique_constraint(None, ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date_create')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
