"""empty message

Revision ID: 5045bbd4a0ee
Revises: 5ab641d27e47
Create Date: 2024-03-08 14:09:38.467502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5045bbd4a0ee'
down_revision = '5ab641d27e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False))
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
