"""empty message

Revision ID: 5063cae65e7e
Revises: b75ac5c5e89e
Create Date: 2026-05-31 14:14:19.948493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5063cae65e7e'
down_revision = 'b75ac5c5e89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###
