"""empty message

Revision ID: 5241137aebd0
Revises: 4e161110f948
Create Date: 2024-02-14 21:38:45.217192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5241137aebd0'
down_revision = '4e161110f948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_phones',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('partner_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('phone_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_phones')
    # ### end Alembic commands ###
