"""empty message

Revision ID: 594a5f47b6d6
Revises: 4c3683bd247e
Create Date: 2024-02-21 15:39:13.528773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '594a5f47b6d6'
down_revision = '4c3683bd247e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_gifted',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('gifted_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('gifted_name', sa.String(length=80), nullable=False),
    sa.Column('gift_ocasion', sa.String(length=80), nullable=False),
    sa.Column('signature_card', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=True, comment='message'),
    sa.ForeignKeyConstraint(['gifted_id'], ['clients.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_gifted')
    # ### end Alembic commands ###
