"""empty message

Revision ID: 5ab641d27e47
Revises: 268d283ecd2c
Create Date: 2024-03-08 14:05:03.247585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ab641d27e47'
down_revision = '268d283ecd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.drop_constraint('client_gifted_ibfk_1', type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('client_gifted_ibfk_1', 'clients', ['client_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###
