"""empty message

Revision ID: 5ad871988d08
Revises: 646481843d00
Create Date: 2024-03-11 17:16:51.381169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ad871988d08'
down_revision = '646481843d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False))
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
