"""empty message

Revision ID: 65e5d710cd90
Revises: d909a34cddcd
Create Date: 2026-05-19 08:43:07.830806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e5d710cd90'
down_revision = 'd909a34cddcd'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###
