"""empty message

Revision ID: 67d60325a539
Revises: ab06015eb136
Create Date: 2024-11-18 14:20:31.858427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d60325a539'
down_revision = 'ab06015eb136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basket_description', sa.String(length=80), nullable=False))
        batch_op.drop_column('description')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_description', sa.String(length=80), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False))
        batch_op.drop_column('product_description')

    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False))
        batch_op.drop_column('basket_description')

    # ### end Alembic commands ###
