"""empty message

Revision ID: 7402a13423e2
Revises: 28210e826e93
Create Date: 2024-06-14 16:22:21.708617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7402a13423e2'
down_revision = '28210e826e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('path',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               existing_nullable=True)

    # ### end Alembic commands ###
