"""empty message

Revision ID: 75b52dd77001
Revises: 1fb1bb679e07
Create Date: 2024-12-13 17:08:37.209954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75b52dd77001'
down_revision = '1fb1bb679e07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_id', mysql.INTEGER(unsigned=True), nullable=False))
        batch_op.create_foreign_key(None, 'checkout', ['checkout_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkout_basket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('checkout_id')

    # ### end Alembic commands ###
