"""empty message

Revision ID: 77f30fa7a154
Revises: 5045bbd4a0ee
Create Date: 2024-03-08 14:29:00.991505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77f30fa7a154'
down_revision = '5045bbd4a0ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gifted_ocasion', sa.String(length=80), nullable=False))
        batch_op.drop_column('gift_ocasion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gift_ocasion', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False))
        batch_op.drop_column('gifted_ocasion')

    # ### end Alembic commands ###
