"""empty message

Revision ID: 7f267b0f5bba
Revises: b43b76f2c686
Create Date: 2024-03-25 10:34:21.148109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f267b0f5bba'
down_revision = 'b43b76f2c686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True))
        batch_op.create_index(batch_op.f('ix_categories_status'), ['status'], unique=False)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True))
        batch_op.create_index(batch_op.f('ix_units_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_status'))
        batch_op.drop_column('status')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
