"""empty message

Revision ID: 81761e921367
Revises: be2216f62052
Create Date: 2024-03-01 10:38:20.858485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81761e921367'
down_revision = 'be2216f62052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True))
        batch_op.create_index(batch_op.f('ix_clients_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
