"""empty message

Revision ID: 86cfa44d8cbc
Revises: 12e198d0c100
Create Date: 2026-05-06 08:21:31.250347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86cfa44d8cbc'
down_revision = '12e198d0c100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.String(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.String(length=40),
               type_=mysql.DECIMAL(precision=10, scale=0),
               nullable=False)

    # ### end Alembic commands ###
