"""empty message

Revision ID: 9034d1a7281f
Revises: 3967825f1d9b
Create Date: 2024-03-08 09:44:35.412675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9034d1a7281f'
down_revision = '3967825f1d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gifted_phones')
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_country', sa.String(length=4), server_default='55', nullable=False))
        batch_op.add_column(sa.Column('code_area', sa.String(length=4), nullable=False))
        batch_op.add_column(sa.Column('number', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.drop_column('number')
        batch_op.drop_column('code_area')
        batch_op.drop_column('code_country')

    op.create_table('gifted_phones',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('gifted_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('phone_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('date_create', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['gifted_id'], ['client_gifted.id'], name='gifted_phones_ibfk_1', onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], name='gifted_phones_ibfk_2', onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
