"""empty message

Revision ID: a8ec7eae1ce4
Revises: bab53bccdc22
Create Date: 2024-03-11 16:26:37.252255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a8ec7eae1ce4'
down_revision = 'bab53bccdc22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_name', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=28), nullable=True),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))

    op.drop_table('users')
    # ### end Alembic commands ###
