"""empty message

Revision ID: ab06015eb136
Revises: 33ec7c470915
Create Date: 2024-11-18 11:27:41.194891

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab06015eb136'
down_revision = '33ec7c470915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_description', sa.String(length=40), nullable=False))
        batch_op.drop_index('description')
        batch_op.create_unique_constraint(None, ['unit_description'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('description', ['description'], unique=True)
        batch_op.drop_column('unit_description')

    # ### end Alembic commands ###
