"""empty message

Revision ID: b13ec9eb79b7
Revises: 11b75e923ddd
Create Date: 2025-07-22 10:50:49.865529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b13ec9eb79b7'
down_revision = '11b75e923ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('cart', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_cart_status'))
    #     batch_op.drop_index(batch_op.f('time_slot'))
    #     batch_op.drop_index(batch_op.f('uuid'))

    # op.drop_table('cart')
    # with op.batch_alter_table('cart_basket', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('order_id', mysql.INTEGER(unsigned=True), nullable=False))
    #     batch_op.drop_constraint(batch_op.f('cart_basket_ibfk_2'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], onupdate='CASCADE')
    #     batch_op.drop_column('cart_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uuid'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('orders_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Numeric(), nullable=False))
        batch_op.drop_index(batch_op.f('uuid'))
        batch_op.drop_column('uuid')
        batch_op.drop_column('qtd')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uuid'))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
        batch_op.create_index(batch_op.f('uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('orders_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtd', mysql.DECIMAL(precision=10, scale=0), nullable=False))
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
        batch_op.create_index(batch_op.f('uuid'), ['uuid'], unique=True)
        batch_op.drop_column('quantity')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
        batch_op.create_index(batch_op.f('uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('cart_basket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('cart_basket_ibfk_2'), 'cart', ['cart_id'], ['id'], onupdate='CASCADE')
        batch_op.drop_column('order_id')

    op.create_table('cart',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('value', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('voucher', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('total', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('discount', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('subtotal', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('delivery', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('status', mysql.ENUM('disabled', 'enabled', 'deleted', 'inactive'), server_default=sa.text("'enabled'"), nullable=True),
    sa.Column('payment_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=40), nullable=True),
    sa.Column('date_delivery', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('time_slot', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('date_create', mysql.DECIMAL(precision=15, scale=3), nullable=False),
    sa.Column('quantity', mysql.DECIMAL(precision=15, scale=0), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uuid'), ['uuid'], unique=True)
        batch_op.create_index(batch_op.f('time_slot'), ['time_slot'], unique=True)
        batch_op.create_index(batch_op.f('ix_cart_status'), ['status'], unique=False)

    # ### end Alembic commands ###
