"""empty message

Revision ID: b43b76f2c686
Revises: e644fb5c535c
Create Date: 2024-03-22 16:31:47.529237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b43b76f2c686'
down_revision = 'e644fb5c535c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True))
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_products_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_status'))
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
