"""empty message

Revision ID: b8d8d6b5eb0e
Revises: 035e96fd478e
Create Date: 2025-07-17 15:22:49.109052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8d8d6b5eb0e'
down_revision = '035e96fd478e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders_items',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('product_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('order_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('qtd', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('disabled', 'enabled', 'deleted', 'inactive', name='statusenum'), server_default='enabled', nullable=True),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('orders_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_items_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_items_status'))

    op.drop_table('orders_items')
    # ### end Alembic commands ###
