"""empty message

Revision ID: bab53bccdc22
Revises: 77f30fa7a154
Create Date: 2024-03-09 16:07:16.093098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bab53bccdc22'
down_revision = '77f30fa7a154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.alter_column('gifted_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=True)
        batch_op.alter_column('gifted_ocasion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=True)
        batch_op.alter_column('signature_card',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=True)
        batch_op.alter_column('code_country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4),
               nullable=True,
               existing_server_default=sa.text("'55'"))
        batch_op.alter_column('code_area',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4),
               nullable=True)
        batch_op.alter_column('number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15),
               nullable=False)
        batch_op.alter_column('code_area',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4),
               nullable=False)
        batch_op.alter_column('code_country',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=4),
               nullable=False,
               existing_server_default=sa.text("'55'"))
        batch_op.alter_column('signature_card',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=False)
        batch_op.alter_column('gifted_ocasion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=False)
        batch_op.alter_column('gifted_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80),
               nullable=False)

    # ### end Alembic commands ###
