"""empty message

Revision ID: bb926c145500
Revises: 7853e959fb52
Create Date: 2024-03-04 08:47:03.974748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb926c145500'
down_revision = '7853e959fb52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.drop_index('uuid')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('phones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
        batch_op.create_index('uuid', ['uuid'], unique=True)

    # ### end Alembic commands ###
