"""add address fields to checkout

Revision ID: bc77f8739b57
Revises: 154c9f869763
Create Date: 2026-04-30 11:01:30.527535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc77f8739b57'
down_revision = '154c9f869763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zip_code', sa.String(length=9), nullable=False))
        batch_op.add_column(sa.Column('street', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('street_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('complement', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('district', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkouts', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('district')
        batch_op.drop_column('complement')
        batch_op.drop_column('street_number')
        batch_op.drop_column('street')
        batch_op.drop_column('zip_code')

    # ### end Alembic commands ###
