"""empty message

Revision ID: be2216f62052
Revises: 4ae848929101
Create Date: 2024-03-01 10:36:00.185830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be2216f62052'
down_revision = '4ae848929101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('ix_clients_status')
        batch_op.drop_index('type')
        batch_op.drop_index('uuid')
        batch_op.drop_column('type')
        batch_op.drop_column('email')
        batch_op.drop_column('uuid')
        batch_op.drop_column('date_create')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.ENUM('disabled', 'enabled', 'deleted', 'inactive', collation='utf8mb4_unicode_ci'), server_default=sa.text("'enabled'"), nullable=True))
        batch_op.add_column(sa.Column('date_create', mysql.DECIMAL(precision=15, scale=3), nullable=True))
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=36), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=2), nullable=True))
        batch_op.create_index('uuid', ['uuid'], unique=True)
        batch_op.create_index('type', ['type'], unique=True)
        batch_op.create_index('ix_clients_status', ['status'], unique=False)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
