"""empty message

Revision ID: c3a102036eeb
Revises: 65e5d710cd90
Create Date: 2026-05-19 08:43:35.163889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a102036eeb'
down_revision = '65e5d710cd90'
branch_labels = None
depends_on = None


def upgrade():
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###
