"""empty message

Revision ID: c788598dd945
Revises: efb10a3b8fe0
Create Date: 2024-06-24 13:38:44.019024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c788598dd945'
down_revision = 'efb10a3b8fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_type', mysql.INTEGER(unsigned=True), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('category_type')

    # ### end Alembic commands ###
