"""empty message

Revision ID: cd72532876e5
Revises: 39061671c67b
Create Date: 2026-05-19 08:41:17.102451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd72532876e5'
down_revision = '39061671c67b'
branch_labels = None
depends_on = None


def upgrade():
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###
