"""empty message

Revision ID: d21aca8cd6f8
Revises: eef7eaee4f47
Create Date: 2024-03-07 17:17:03.451150

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd21aca8cd6f8'
down_revision = 'eef7eaee4f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gifted_phones',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('gifted_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('phone_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['gifted_id'], ['client_gifted.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gifted_phones')
    # ### end Alembic commands ###
