"""empty message

Revision ID: d909a34cddcd
Revises: bbe12860c27a
Create Date: 2026-05-19 08:42:25.864068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd909a34cddcd'
down_revision = 'bbe12860c27a'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###
