"""empty message

Revision ID: d9b9a85c3435
Revises: 29b644be9590
Create Date: 2024-03-01 23:38:10.563173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b9a85c3435'
down_revision = '29b644be9590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=2), nullable=False))
        batch_op.create_unique_constraint(None, ['type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
