"""empty message

Revision ID: da5cb5c192b6
Revises: b13ec9eb79b7
Create Date: 2025-07-22 11:31:37.215340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da5cb5c192b6'
down_revision = 'b13ec9eb79b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_basket',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('basket_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('order_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_basket')
    # ### end Alembic commands ###
