"""empty message

Revision ID: e379e4f22113
Revises: e9d120e23aa6
Create Date: 2024-03-01 10:27:08.066625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e379e4f22113'
down_revision = 'e9d120e23aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index('uuid')
        batch_op.drop_column('uuid')
        batch_op.drop_column('date_create')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', mysql.DECIMAL(precision=15, scale=3), nullable=False))
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
        batch_op.create_index('uuid', ['uuid'], unique=True)

    # ### end Alembic commands ###
