"""empty message

Revision ID: e9d120e23aa6
Revises: 2deee5a55c7b
Create Date: 2024-03-01 09:35:51.817681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9d120e23aa6'
down_revision = '2deee5a55c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_phones',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('phone_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('date_create', sa.DECIMAL(precision=15, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB',
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_phones')
    # ### end Alembic commands ###
