"""empty message

Revision ID: eef7eaee4f47
Revises: e10fe38cc82a
Create Date: 2024-03-07 16:43:35.586996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eef7eaee4f47'
down_revision = 'e10fe38cc82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', mysql.INTEGER(unsigned=True), nullable=False))
        batch_op.drop_index('uuid')
        batch_op.drop_constraint('client_gifted_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'clients', ['client_id'], ['id'], onupdate='CASCADE')
        batch_op.drop_column('gifted_id')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_gifted', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False))
        batch_op.add_column(sa.Column('gifted_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('client_gifted_ibfk_1', 'clients', ['gifted_id'], ['id'], onupdate='CASCADE')
        batch_op.create_index('uuid', ['uuid'], unique=True)
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
