"""empty message

Revision ID: f84004b811e9
Revises: 45acec69fd4e
Create Date: 2024-03-18 15:35:42.198215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f84004b811e9'
down_revision = '45acec69fd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(unsigned=True), nullable=False))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
