"""empty message

Revision ID: ff34e4ea4bc2
Revises: 594a5f47b6d6
Create Date: 2024-02-22 10:10:47.623168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff34e4ea4bc2'
down_revision = '594a5f47b6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_delivery', sa.DECIMAL(precision=15, scale=3), nullable=False))
        batch_op.add_column(sa.Column('time_slot', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['time_slot'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('time_slot')
        batch_op.drop_column('date_delivery')

    # ### end Alembic commands ###
